#####################################################################################
# +-------------------------------------------------------------------------------+ #
# |     ____                     _  _            _____        _                   | #
# |    / ___| _ __  __ _ __   __(_)| |_  _   _  |_   _|_   _ | |__    ___  ___    | #
# |   | |  _ | '__|/ _` |\ \ / /| || __|| | | |   | | | | | || '_ \  / _ \/ __|   | #
# |   | |_| || |  | (_| | \ V / | || |_ | |_| |   | | | |_| || |_) ||  __/\__ \   | #
# |    \____||_|   \__,_|  \_/  |_| \__| \__, |   |_|  \__,_||_.__/  \___||___/   | #
# |                                      |___/                                    | #
# | By: Benz56                                                                    | #
# +-------------------------------------------------------------------------------+ #
#####################################################################################


# Control if players should be able to descend by sneaking when inside a Gravity Tube.
SneakToFall: true

# Should fall damage in Gravity Tubes be disabled when players fall by sneaking?
DisableFallDamage: true

# You can enable a BossBar to show how far the player is in the Gravity Tube.
BossBarEnabled: true

# Color: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
BossBarColor: RED

# Style: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
BossBarStyle: SOLID

# Set the message above the BossBar. Supported placeholder:
# %percentage% - Shows how far the player is in percentage.
BossBarTitle: '&l%percentage%%'

# Should players be allowed to use Gravity Tubes when in combat?
# Requires the CombatLogX plugin.
DisableInCombat: false

# Update Checker.
# Enable or disable the update checker.
UpdateCheckerEnabled: true
# false: All OPs are notified of a new update when they join.
# true: OPs are only notified if they have the gravitytubes.update permission as well.
# N.B. any user with the gravitytubes.update permission is notified; OP or not.
UpdateCheckerPermissionOnly: false