#####################################################################################
# +-------------------------------------------------------------------------------+ #
# |     ____                     _  _            _____        _                   | #
# |    / ___| _ __  __ _ __   __(_)| |_  _   _  |_   _|_   _ | |__    ___  ___    | #
# |   | |  _ | '__|/ _` |\ \ / /| || __|| | | |   | | | | | || '_ \  / _ \/ __|   | #
# |   | |_| || |  | (_| | \ V / | || |_ | |_| |   | | | |_| || |_) ||  __/\__ \   | #
# |    \____||_|   \__,_|  \_/  |_| \__| \__, |   |_|  \__,_||_.__/  \___||___/   | #
# |                                      |___/                                    | #
# | By: Benz56                                                                    | #
# +-------------------------------------------------------------------------------+ #
#####################################################################################


# Control if players should be able to descend by sneaking when inside a Gravity Tube.
SneakToFall: true

# Should fall damage in Gravity Tubes be disabled when players fall by sneaking?
DisableFallDamage: true

# Update Checker.
# false: All OPs are notified of a new update when they join.
# true: OPs are only notified if they have the gravitytubes.update permission as well.
# N.B. any user with the gravitytubes.update permission is notified; OP or not.
UpdateCheckerPermissionOnly: false